# Charge automatiquement les variables depuis .env en local (lancement depuis backend/ ou racine)
spring.config.import=optional:file:../.env[.properties],optional:file:.env[.properties]

# Nom de l'application 
spring.application.name=walletly backend

# Port du serveur
server.port=8081

# JWT 
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Configuration de la base PostgreSQL

#L’URL de connexion à ta base PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
#Ton identifiant PostgreSQL (souvent postgres)
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#Ton mot de passe PostgreSQL
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuration JPA / Hibernate = JPA les régles du jeu  // HIbernate = celui qui réalise, qui fait le travail. 

#Crée/modifie les tables automatiquement selon les entités = “Regarde mes classes Java (mes entités) et mets à jour les tables automatiquement.”
spring.jpa.hibernate.ddl-auto=update
#Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true 
#Indique à Hibernate que tu utilises PostgreSQL = “J’utilise PostgreSQL, adapte ton SQL en conséquence.”
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

