# Nom de l'application 
spring.application.name=Smart Budget Backend

# Port du serveur
server.port=8081

# JWT 
jwt.secret=my_super_secret_key_my_super_secret_key_12345
jwt.expiration=86400000

# Configuration de la base PostgreSQL

#L’URL de connexion à ta base PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/smartbudget 
#Ton identifiant PostgreSQL (souvent postgres)
spring.datasource.username=postgres
#Ton mot de passe PostgreSQL
spring.datasource.password=postgres

# Configuration JPA / Hibernate = JPA les régles du jeu  // HIbernate = celui qui réalise, qui fait le travail. 

#Crée/modifie les tables automatiquement selon les entités = “Regarde mes classes Java (mes entités) et mets à jour les tables automatiquement.”
spring.jpa.hibernate.ddl-auto=update
#Affiche les requêtes SQL dans la console
spring.jpa.show-sql=true 
#Indique à Hibernate que tu utilises PostgreSQL = “J’utilise PostgreSQL, adapte ton SQL en conséquence.”
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

